### ISSUE TITLE
dockerswarm.rocks is deprecated

### ISSUE THREAD

**Issue by d630** [BretFisher/awesome-swarm#34]
I noticed that the dockerswarm.rocks website listed here is deprecated as of december 2023. They say, "Kubernetes simply won" and "it's not sensitive to build a new product using Docker Swarm Mode".[1] Can you recommend an in-depth discussion about whether or not Docker Engine together with Swarm should be used in production on this topic? Or maybe you guys could take a stand?

[1] https://dockerswarm.rocks/swarm-or-kubernetes/

**Comment by BretFisher** [comment]
Comparing these two orchestrators has been a common question and discussion for over 5 years, and I've discussed it dozens of times on my YouTube Live show, in my Udemy course Q&A's, and my blog. What I don't have is a definitive, updated, full FAQ on what you're looking for.

In [our Discord](https://devops.fan), we have a bi-monthly Swarm Fans meetup, where people using Swarm discuss their solutions to common problems in the 2nd (or 3rd behind Nomad) most popular container orchestrator. You're welcome to join.

The bottom line is, if Swarm meets your needs, then great, keep using it. There's no single container orchestrator for everyone, and people that try out Swarm first, might stick with it, or might find they need something more advanced and move to Kubernetes. 

Swarm gets features and fixes in each Docker release (which I talked about in our Discord and last Swarm Fans meetup recently). People still buy my Swarm courses daily. Nearly ever Q&A live stream I have, people ask about Swarm... so I get a sense that plenty of people still find it useful and solve problems with it. It just doesn't have a billion-dollar industry of hundreds of companies trying to sell solutions for it (like Kubernetes).

Sebastián Ramírez is great, and Swarm fans love his work on that site. It's too bad he felt he needed to post those comments, and you can [see by the thread that not everyone agrees](https://github.com/tiangolo/dockerswarm.rocks/issues/89).

**Comment by s4ke** [comment]
There is not much to add to what Bret already wrote here. It all boils down to this in my opinion:

> The bottom line is, if Swarm meets your needs, then great, keep using it. There's no single container orchestrator for everyone, and people that try out Swarm first, might stick with it, or might find they need something more advanced and move to Kubernetes.

At my company, we are and will continue to be using Docker Swarm in production. We have been burnt by a very bad k8s experience and actually thought that Orchestration was not for us. At first we were scared to try out Docker Swarm because of the misinformation around its future that keeps getting brought up. Turns out it does everything we need it to do. I doubt that we will outgrow it anytime soon.

P.S.: While we are currently not using Kubernetes, this does not mean we will never. It is a good solution for many and it does exist for a reason.

**Comment by tomdaley92** [comment]
I came here because I'm confused by what's stated [here](https://dockerswarm.rocks/swarm-or-kubernetes/).

Forgive me if I sound like a broken record, but Docker Swarm (classic) is what Mirantis picked up, was it not? That's the old Enterprises offering that came well before swarm mode was integrated into the docker engine.

Docker Swarm mode is a completely different product that's built in to the docker engine and uses the Moby swarmkit repo as upstream, and is still active and maintained not owned my Mirantis, right? Am I mistaken?

I still use docker swarm mode in production at work and outside of work. Just upgraded to Docker major version 25 and swarm mode is still rock solid for small teams/projects.

As far as other orchestration alternatives to Kubernetes, there's a nice middle ground one from Hashicorp, called Nomad I believe.

**Comment by BretFisher** [comment]
Docker Swarm "classic", which was installed as containers on top of Docker Engine, isn't used/supported by anyone I know.

Docker Swarm Mode, or just Swarm, which is built into all Docker Engine installs, is indeed what was built into Docker Enterprise, which was acquired by Marantis (they only acquired the closed-source enterprise solution.) Docker and Mirantis have maintained the SwarmKit repo since (and downstream integrations like Docker CLI/Engine features for Swarm) and Mirantis has provided business-level Swarm support since 2019.

**Comment by tomdaley92** [comment]
Thank you for the clarification @BretFisher !

**Comment by s4ke** [comment]
@tiangolo has graciously adapted the wording and is now linking to this repository. Closing this issue as it seems resolved.
